### ISSUE TITLE
Maybe redesign the communication

### ISSUE THREAD

**Issue by erikgoe** [JulianSobott/Catan#11]
The current implementation seems to be a little bit chaotic and does not really make use of the advantages of our interface design. Maybe we could redesign the interface of *RemoteDataClient* and *LocalDataServer* corresponding to this example:
```
LOCAL
* UI.diceBtn clicked
* localDataServer.roll_dice() /* impl from DataIfc */
* core.roll_dice()
* localDataServer.dice_resut()
   * <to all clients>: result()
   * ui.result()

REMOTE
UI.diceBtn clicked
* remoteDataClient.roll_dice /* impl from DataIfc */
   * to server: send_message(new Packet(...))
   <on server>: localDataServer.roll_dice() /* now the same procedure as if had been local */
   ...
   <from server>: result()
   * ui.result()
```

This way we can omit obsolete packaging and duplicate code as in https://github.com/JulianSobott/Catan/blob/bfdd2eb91b994e27bba34e91071aa32ac1dc44ea/src/network/LocalDataServer.java#L83-L136

**Comment by JulianSobott** [comment]
I think we can close this issue or is something left?
