### ISSUE TITLE
Building bugs

### ISSUE THREAD

**Issue by erikgoe** [JulianSobott/Catan#20]
1. Streets can be build across buildings of another party
2. Settlements can be build on top of settlements of another party

I'll fix those issues later. Just to remind myself...

**Comment by JulianSobott** [comment]
![grafik](https://user-images.githubusercontent.com/23342096/36642074-200c02fc-1a3a-11e8-856b-5710620b3b04.png)
This happens when playing with more than 2 player

**Comment by erikgoe** [comment]
Are these the random houses?

**Comment by JulianSobott** [comment]
Yes, right after the initialization

**Comment by erikgoe** [comment]
Ok I'll fix this later
